name: Website built and deploy
on: push
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        php-version:
          - 7.4
    steps:
      - uses: actions/checkout@v2
      - name: 'Install PHP {{ matrix.php-version }}'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php-version }}'
      - name: Build Couscous site
        run: |
          curl -OS http://couscous.io/couscous.phar
          chmod +x couscous.phar
          sudo mv couscous.phar /usr/local/bin/couscous
          couscous generate
  release:
    runs-on: '${{ matrix.os }}'
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        php-version:
          - 7.4
    steps:
      - uses: actions/checkout@v2
      - name: 'Install PHP {{ matrix.php-version }}'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php-version }}'
      - name: Build Couscous site
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.RELEASE_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.RELEASE_AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.WEBSITE_S3_BUCKET }}
        run: |
          curl -OS http://couscous.io/couscous.phar
          chmod +x couscous.phar
          sudo mv couscous.phar /usr/local/bin/couscous
          couscous generate
          pip install --user awscli
          aws s3 sync .couscous/generated/ "s3://$S3_BUCKET/"
